/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatorio;

import obligatorio.Entities.User;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.Map.Entry;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import obligatorio.Connect;
import static obligatorio.Dashboard.user;

/**
 *
 * @author Antonio
 */
public class AddProduct extends javax.swing.JPanel {

    Connect conn;
    Connection reg;

    private int idProducto;
    private Map<String, String> categoryMap;

    /**
     * Creates new form Principal
     */
    public AddProduct(Map<String, String> categories) throws SQLException {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        categoryMap = categories;
        initCategoryCB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        nameTitle = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        priceTitle = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        categoryTitle = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        descriptionTitle = new javax.swing.JLabel();
        input_description = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        btn_saveChanges = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cb_category = new javax.swing.JComboBox<>();
        sp_price = new javax.swing.JSpinner();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Nuevo Producto");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        nameTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTitle.setText("Nombre:");
        add(nameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, -1));

        input_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_name.setForeground(new java.awt.Color(102, 102, 102));
        input_name.setText("Ingrese el nombre");
        input_name.setBorder(null);
        input_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_nameMousePressed(evt);
            }
        });
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });
        add(input_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 160, 20));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 10));

        priceTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        priceTitle.setText("Precio en UC$:");
        add(priceTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 100, -1));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 10));

        categoryTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        categoryTitle.setText("Categoria:");
        add(categoryTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 70, -1));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 260, 10));

        descriptionTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        descriptionTitle.setText("Descripcion:");
        add(descriptionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, -1));

        input_description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_description.setForeground(new java.awt.Color(102, 102, 102));
        input_description.setText("Ingrese descripción");
        input_description.setBorder(null);
        input_description.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_descriptionMousePressed(evt);
            }
        });
        input_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_descriptionActionPerformed(evt);
            }
        });
        add(input_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 160, 20));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 10));

        btn_saveChanges.setBackground(new java.awt.Color(18, 90, 173));
        btn_saveChanges.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_saveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveChangesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveChangesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_saveChangesMousePressed(evt);
            }
        });
        btn_saveChanges.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Agregar Producto");
        jLabel10.setToolTipText("");
        btn_saveChanges.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 160, -1));

        add(btn_saveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 260, 50));

        cb_category.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_category.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_categoryActionPerformed(evt);
            }
        });
        add(cb_category, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, -1));

        sp_price.setModel(new javax.swing.SpinnerNumberModel());
        add(sp_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 110, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void input_nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_nameMousePressed
        if (input_name.getText().equals("Ingrese el nombre")) {
            input_name.setText("");
        }
        if (input_description.getText().equals("") || input_description.getText() == null || input_description.getText().equals(" ")) {
            input_description.setText("Ingrese descripción");
        }
    }//GEN-LAST:event_input_nameMousePressed

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void btn_saveChangesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveChangesMouseEntered
        setColorSaveButton(btn_saveChanges);
    }//GEN-LAST:event_btn_saveChangesMouseEntered

    private void btn_saveChangesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveChangesMouseExited
        resetColorSaveButton(btn_saveChanges);
    }//GEN-LAST:event_btn_saveChangesMouseExited

    private void btn_saveChangesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveChangesMousePressed
        try {
            executeInsertProduct();
        } catch (SQLException ex) {
            Logger.getLogger(AddProduct.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_saveChangesMousePressed

    private void input_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_descriptionActionPerformed

    private void input_descriptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_descriptionMousePressed
        if (input_name.getText().equals("") || input_name.getText() == null || input_name.getText().equals(" ")) {
            input_name.setText("Ingrese el nombre");
        }
        if (input_description.getText().equals("Ingrese descripción")) {
            input_description.setText("");
        }
    }//GEN-LAST:event_input_descriptionMousePressed

    private void cb_categoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_categoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_categoryActionPerformed

    public void initCategoryCB() {
        this.cb_category.removeAllItems();
        for (Entry e : this.categoryMap.entrySet()) {
            cb_category.addItem(e.getValue().toString());
        }
    }

    public void executeInsertProduct() throws SQLException {
        if (input_name.getText().equals("Ingrese el nombre") || input_description.getText().equals("Ingrese descripción")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            input_name.requestFocus();
        } else {
            String newName = input_name.getText();
            int newPrice = (Integer) sp_price.getValue();
            String newDescription = input_description.getText();

            if (newName == null || "".equals(newName) || input_description == null || "".equals(input_description)) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debe llenar todos los campos \n", "AVISO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
                input_name.requestFocus();
            } else {
                Statement stm = reg.createStatement();
                stm.executeUpdate("INSERT INTO \"Producto\" (\"IdProducto\", \"Nombre\", \"Precio\", \"DescripcionProducto\", "
                        + "\"IdUsuario\", \"IdCategoria\", \"Estado\")  VALUES('" + getProductId() + "', '" + newName + "', '"
                        + newPrice + "', '" + newDescription + "', '" + user.getId() + "', '" + (cb_category.getSelectedIndex() + 1) + "', 'True')");
                input_name.setText("");
                input_description.setText("");
                sp_price.setValue(0);
                javax.swing.JOptionPane.showMessageDialog(this, "El Producto agregado correctamente \n", "HECHO", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    public int getProductId() throws SQLException {
        String SQL_QUERY_PRODUCT = "SELECT * FROM \"Producto\"";

        Statement statement = reg.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        ResultSet resultSet = statement.executeQuery(SQL_QUERY_PRODUCT);
        int count = 0;
        while (resultSet.next()) {
            count = Integer.parseInt(resultSet.getString("IdProducto")) > count ? Integer.parseInt(resultSet.getString("IdProducto")) : count;
        }
        return count + 1;
    }

    void setColorSaveButton(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColorSaveButton(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btn_saveChanges;
    private javax.swing.JLabel categoryTitle;
    private javax.swing.JComboBox<String> cb_category;
    private javax.swing.JLabel descriptionTitle;
    private javax.swing.JTextField input_description;
    private javax.swing.JTextField input_name;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JLabel priceTitle;
    private javax.swing.JSpinner sp_price;
    // End of variables declaration//GEN-END:variables
}
