/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatorio;

import obligatorio.Entities.User;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static obligatorio.Dashboard.user;

/**
 *
 * @author Antonio
 */
public class InternalBarter extends javax.swing.JPanel {

    Connect conn;

    Connection reg;

    /**
     * Creates new form Principal
     */
    public InternalBarter() throws SQLException {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        this.getUserAddress();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        desc1 = new javax.swing.JLabel();
        desc2 = new javax.swing.JLabel();
        nameTitle = new javax.swing.JLabel();
        cb_products = new javax.swing.JComboBox<>();
        jSeparator4 = new javax.swing.JSeparator();
        AmountTitle = new javax.swing.JLabel();
        sp_amount = new javax.swing.JSpinner();
        jSeparator3 = new javax.swing.JSeparator();
        btn_saveChanges = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        nameTitle1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Obtener UCUCoin");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        desc1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        desc1.setText("otorgarle UCUCoins que seran acreditadas a su cuenta.");
        add(desc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        desc2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        desc2.setText("Seleccione uno de los posibles articulos que la institución puede recibir y a cambio ");
        add(desc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        nameTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTitle.setText("Producto:");
        add(nameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 80, -1));

        cb_products.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_productsActionPerformed(evt);
            }
        });
        add(cb_products, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 190, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 260, 10));

        AmountTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        AmountTitle.setText("Cantidad:");
        add(AmountTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));
        add(sp_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 70, -1));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 260, 10));

        btn_saveChanges.setBackground(new java.awt.Color(18, 90, 173));
        btn_saveChanges.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_saveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveChangesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveChangesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_saveChangesMousePressed(evt);
            }
        });
        btn_saveChanges.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Guardar cambios");
        jLabel10.setToolTipText("");
        btn_saveChanges.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, -1));

        add(btn_saveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, 50));

        nameTitle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTitle1.setText("Total UCUCoins:");
        add(nameTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 100, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setText("X");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 300, 190, 20));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 260, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_saveChangesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveChangesMouseEntered
        setColorSaveButton(btn_saveChanges);
    }//GEN-LAST:event_btn_saveChangesMouseEntered

    private void btn_saveChangesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveChangesMouseExited
        resetColorSaveButton(btn_saveChanges);
    }//GEN-LAST:event_btn_saveChangesMouseExited

    private void btn_saveChangesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveChangesMousePressed
        try {
            this.updateUserInfo();
        } catch (SQLException ex) {
            Logger.getLogger(InternalBarter.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_saveChangesMousePressed

    private void cb_productsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_productsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_productsActionPerformed

    public void getUserAddress() throws SQLException {
        String list[][] = new String[1][5];

        Statement statement = reg.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        String sql = "SELECT * FROM \"Direccion\" WHERE \"IdDireccion\" = " + user.getIdAddress() + ";";
        ResultSet re = statement.executeQuery(sql);

        int i = 0;
        while (re.next()) {
            list[i][0] = re.getString("IdDireccion");
            list[i][1] = re.getString("Calle");
            list[i][2] = re.getString("NumeroPuerta");
            list[i][3] = re.getString("Esquina");
            list[i][4] = re.getString("Descripcion");
            i++;
        }

//        this.street.setText(list[0][1]);
//        this.doorNumber.setText(list[0][2]);
//        this.street2.setText(list[0][3]);
//        this.description.setText(list[0][4]);
    }

    public void updateUserInfo() throws SQLException {
//        String newName = !"".equals(input_name.getText()) ? input_name.getText() : name.getText();
//        String newLastName = !"".equals(input_lastName.getText()) ? input_lastName.getText() : lastName.getText();
//        String newPhone = !"".equals(input_phone.getText()) ? input_phone.getText() : phone.getText();
//        String newEmail = !"".equals(input_email.getText()) ? input_email.getText() : email.getText();

        Statement stmt = reg.createStatement();
//        String sqlUsuario = "UPDATE \"Usuario\" SET \"Nombre\" = '" + newName + "', \"Apellido\" = '" + newLastName + "', \"Telefono\" = '" + newPhone + "', \"Mail\" = '" + newEmail + "' WHERE \"IdUsuario\" = " + user.getId() + ";";
//        stmt.executeUpdate(sqlUsuario);

//        String newStreet = !"".equals(input_street.getText()) ? input_street.getText() : street.getText();
//        String newDoorNumber = !"".equals(input_doorNumber.getText()) ? input_doorNumber.getText() : doorNumber.getText();
//        String newStreet2 = !"".equals(input_street2.getText()) ? input_street2.getText() : street2.getText();
//        String newDescripcion = !"".equals(input_description.getText()) ? input_description.getText() : description.getText();
//        String sqlDireccion = "UPDATE \"Direccion\" SET \"Calle\" = '" + newStreet + "', \"NumeroPuerta\" = " + newDoorNumber + ", \"Esquina\" = '" + newStreet2 + "', \"Descripcion\" = '" + newDescripcion + "' WHERE \"IdDireccion\" = " + user.getIdAddress() + ";";
//        stmt.executeUpdate(sqlDireccion);
    }

    void setColorSaveButton(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColorSaveButton(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AmountTitle;
    private javax.swing.JLabel Title;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btn_saveChanges;
    private javax.swing.JComboBox<String> cb_products;
    private javax.swing.JLabel desc1;
    private javax.swing.JLabel desc2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JLabel nameTitle1;
    private javax.swing.JSpinner sp_amount;
    // End of variables declaration//GEN-END:variables
}
