/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatorio;

import obligatorio.Entities.User;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import static obligatorio.Dashboard.user;

/**
 *
 * @author Antonio
 */
public class MyInfo extends javax.swing.JPanel {

    Connect conn;

    Connection reg;

    /**
     * Creates new form Principal
     */
    public MyInfo() throws SQLException {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        name.setText(user.getName());
        lastName.setText(user.getLastName());
        phone.setText(user.getPhone());
        email.setText(user.getEmail());
        this.getUserAddress();
        this.disableInputs();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        body = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        nameTitle = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        input_name = new javax.swing.JTextField();
        btn_editName = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lastNameTitle = new javax.swing.JLabel();
        lastName = new javax.swing.JLabel();
        input_lastName = new javax.swing.JTextField();
        btn_editLastName = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        phoneTitle = new javax.swing.JLabel();
        phone = new javax.swing.JLabel();
        input_phone = new javax.swing.JTextField();
        btn_editPhone = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        emailTitle = new javax.swing.JLabel();
        email = new javax.swing.JLabel();
        input_email = new javax.swing.JTextField();
        btn_editEmail = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        addressTitle1 = new javax.swing.JLabel();
        street = new javax.swing.JLabel();
        input_street = new javax.swing.JTextField();
        btn_editStreet = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        addressTitle = new javax.swing.JLabel();
        doorNumber = new javax.swing.JLabel();
        input_doorNumber = new javax.swing.JTextField();
        btn_editDoorNumber = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        addressTitle3 = new javax.swing.JLabel();
        street2 = new javax.swing.JLabel();
        input_street2 = new javax.swing.JTextField();
        btn_editStreet2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator8 = new javax.swing.JSeparator();
        addressTitle2 = new javax.swing.JLabel();
        description = new javax.swing.JLabel();
        input_description = new javax.swing.JTextField();
        btn_editDescription = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        btn_saveChanges = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        body.setBackground(new java.awt.Color(255, 255, 255));
        body.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(body, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Mis Datos Personales");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        nameTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nameTitle.setText("Nombre:");
        add(nameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 60, -1));

        name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        name.setText("X");
        add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 190, 20));

        input_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_name.setBorder(null);
        input_name.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_nameMousePressed(evt);
            }
        });
        input_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_nameActionPerformed(evt);
            }
        });
        add(input_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 190, 20));

        btn_editName.setBackground(new java.awt.Color(18, 90, 173));
        btn_editName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_editName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editNameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editNameMousePressed(evt);
            }
        });
        btn_editName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obligatorio/images/pencil.png"))); // NOI18N
        btn_editName.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        add(btn_editName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 30, 30));

        jSeparator4.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator4.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 260, 10));

        lastNameTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastNameTitle.setText("Apellido:");
        add(lastNameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 60, -1));

        lastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lastName.setText("X");
        add(lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, 20));

        input_lastName.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_lastName.setBorder(null);
        input_lastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_lastNameMousePressed(evt);
            }
        });
        input_lastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_lastNameActionPerformed(evt);
            }
        });
        add(input_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 190, 20));

        btn_editLastName.setBackground(new java.awt.Color(18, 90, 173));
        btn_editLastName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_editLastName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editLastNameMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editLastNameMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editLastNameMousePressed(evt);
            }
        });
        btn_editLastName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obligatorio/images/pencil.png"))); // NOI18N
        btn_editLastName.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        add(btn_editLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 30, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator2.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 260, 10));

        phoneTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phoneTitle.setText("Teléfono:");
        add(phoneTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 60, -1));

        phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        phone.setText("X");
        add(phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 190, -1));

        input_phone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_phone.setBorder(null);
        input_phone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_phoneMousePressed(evt);
            }
        });
        input_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_phoneActionPerformed(evt);
            }
        });
        add(input_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 190, 20));

        btn_editPhone.setBackground(new java.awt.Color(18, 90, 173));
        btn_editPhone.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_editPhone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editPhoneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editPhoneMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editPhoneMousePressed(evt);
            }
        });
        btn_editPhone.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obligatorio/images/pencil.png"))); // NOI18N
        btn_editPhone.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        add(btn_editPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 30, 30));

        jSeparator5.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator5.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 260, 10));

        emailTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        emailTitle.setText("Mail:");
        add(emailTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 60, -1));

        email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        email.setText("X");
        add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 190, 20));

        input_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_email.setBorder(null);
        input_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_emailMousePressed(evt);
            }
        });
        input_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_emailActionPerformed(evt);
            }
        });
        add(input_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 190, 20));

        btn_editEmail.setBackground(new java.awt.Color(18, 90, 173));
        btn_editEmail.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_editEmail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editEmailMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editEmailMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editEmailMousePressed(evt);
            }
        });
        btn_editEmail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obligatorio/images/pencil.png"))); // NOI18N
        btn_editEmail.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        add(btn_editEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, 30, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator6.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 260, 10));

        addressTitle1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressTitle1.setText("Calle:");
        add(addressTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        street.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        street.setText("X");
        add(street, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 170, 20));

        input_street.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_street.setBorder(null);
        input_street.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_streetMousePressed(evt);
            }
        });
        input_street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_streetActionPerformed(evt);
            }
        });
        add(input_street, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 170, 20));

        btn_editStreet.setBackground(new java.awt.Color(18, 90, 173));
        btn_editStreet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_editStreet.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editStreetMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editStreetMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editStreetMousePressed(evt);
            }
        });
        btn_editStreet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obligatorio/images/pencil.png"))); // NOI18N
        btn_editStreet.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        add(btn_editStreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 30, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator3.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 260, 10));

        addressTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressTitle.setText("N de Puerta:");
        add(addressTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, -1, -1));

        doorNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        doorNumber.setText("X");
        add(doorNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 170, 20));

        input_doorNumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_doorNumber.setBorder(null);
        input_doorNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_doorNumberMousePressed(evt);
            }
        });
        input_doorNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_doorNumberActionPerformed(evt);
            }
        });
        add(input_doorNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, 170, 20));

        btn_editDoorNumber.setBackground(new java.awt.Color(18, 90, 173));
        btn_editDoorNumber.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_editDoorNumber.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editDoorNumberMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editDoorNumberMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editDoorNumberMousePressed(evt);
            }
        });
        btn_editDoorNumber.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obligatorio/images/pencil.png"))); // NOI18N
        btn_editDoorNumber.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        add(btn_editDoorNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 120, 30, 30));

        jSeparator7.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator7.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 260, 10));

        addressTitle3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressTitle3.setText("Esquina:");
        add(addressTitle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, -1, -1));

        street2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        street2.setText("X");
        add(street2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 170, 20));

        input_street2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_street2.setBorder(null);
        input_street2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_street2MousePressed(evt);
            }
        });
        input_street2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_street2ActionPerformed(evt);
            }
        });
        add(input_street2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 170, 20));

        btn_editStreet2.setBackground(new java.awt.Color(18, 90, 173));
        btn_editStreet2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_editStreet2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editStreet2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editStreet2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editStreet2MousePressed(evt);
            }
        });
        btn_editStreet2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obligatorio/images/pencil.png"))); // NOI18N
        btn_editStreet2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        add(btn_editStreet2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 160, 30, 30));

        jSeparator8.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator8.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 260, 10));

        addressTitle2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addressTitle2.setText("Descripcion:");
        add(addressTitle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        description.setText("X");
        add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 170, 20));

        input_description.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        input_description.setBorder(null);
        input_description.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                input_descriptionMousePressed(evt);
            }
        });
        input_description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_descriptionActionPerformed(evt);
            }
        });
        add(input_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, 170, 20));

        btn_editDescription.setBackground(new java.awt.Color(18, 90, 173));
        btn_editDescription.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_editDescription.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_editDescriptionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_editDescriptionMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_editDescriptionMousePressed(evt);
            }
        });
        btn_editDescription.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/obligatorio/images/pencil.png"))); // NOI18N
        btn_editDescription.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 30));

        add(btn_editDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 30, 30));

        jSeparator9.setForeground(new java.awt.Color(0, 153, 255));
        jSeparator9.setPreferredSize(new java.awt.Dimension(200, 10));
        add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 260, 10));

        btn_saveChanges.setBackground(new java.awt.Color(18, 90, 173));
        btn_saveChanges.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_saveChanges.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_saveChangesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_saveChangesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_saveChangesMousePressed(evt);
            }
        });
        btn_saveChanges.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Guardar cambios");
        jLabel10.setToolTipText("");
        btn_saveChanges.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 150, -1));

        add(btn_saveChanges, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 260, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editDoorNumberMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editDoorNumberMouseEntered
//        setColor(btn_editName);
    }//GEN-LAST:event_btn_editDoorNumberMouseEntered

    private void btn_editDoorNumberMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editDoorNumberMouseExited
//        resetColor(btn_editName);
    }//GEN-LAST:event_btn_editDoorNumberMouseExited

    private void btn_editDoorNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editDoorNumberMousePressed
        this.doorNumber.setVisible(false);
        this.input_doorNumber.setVisible(true);
        input_doorNumber.setText(doorNumber.getText());
    }//GEN-LAST:event_btn_editDoorNumberMousePressed

    private void btn_editNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editNameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editNameMouseEntered

    private void btn_editNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editNameMouseExited

    private void btn_editNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editNameMousePressed
        this.name.setVisible(false);
        this.input_name.setVisible(true);
        input_name.setText(name.getText());
    }//GEN-LAST:event_btn_editNameMousePressed

    private void btn_editLastNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editLastNameMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editLastNameMouseEntered

    private void btn_editLastNameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editLastNameMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editLastNameMouseExited

    private void btn_editLastNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editLastNameMousePressed
        this.lastName.setVisible(false);
        this.input_lastName.setVisible(true);
        input_lastName.setText(lastName.getText());
    }//GEN-LAST:event_btn_editLastNameMousePressed

    private void btn_editPhoneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editPhoneMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editPhoneMouseEntered

    private void btn_editPhoneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editPhoneMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editPhoneMouseExited

    private void btn_editPhoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editPhoneMousePressed
        this.phone.setVisible(false);
        this.input_phone.setVisible(true);
        input_phone.setText(phone.getText());
    }//GEN-LAST:event_btn_editPhoneMousePressed

    private void btn_editEmailMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editEmailMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editEmailMouseEntered

    private void btn_editEmailMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editEmailMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editEmailMouseExited

    private void btn_editEmailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editEmailMousePressed
        this.email.setVisible(false);
        this.input_email.setVisible(true);
        input_email.setText(email.getText());
    }//GEN-LAST:event_btn_editEmailMousePressed

    private void btn_editStreet2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editStreet2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editStreet2MouseEntered

    private void btn_editStreet2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editStreet2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editStreet2MouseExited

    private void btn_editStreet2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editStreet2MousePressed
        this.street2.setVisible(false);
        this.input_street2.setVisible(true);
        input_street2.setText(street2.getText());
    }//GEN-LAST:event_btn_editStreet2MousePressed

    private void btn_editDescriptionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editDescriptionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editDescriptionMouseEntered

    private void btn_editDescriptionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editDescriptionMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editDescriptionMouseExited

    private void btn_editDescriptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editDescriptionMousePressed
        this.description.setVisible(false);
        this.input_description.setVisible(true);
        input_description.setText(description.getText());
    }//GEN-LAST:event_btn_editDescriptionMousePressed

    private void btn_editStreetMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editStreetMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editStreetMouseEntered

    private void btn_editStreetMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editStreetMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_editStreetMouseExited

    private void btn_editStreetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_editStreetMousePressed
        this.street.setVisible(false);
        this.input_street.setVisible(true);
        input_street.setText(street.getText());
    }//GEN-LAST:event_btn_editStreetMousePressed

    private void input_nameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_nameMousePressed
//        if (input_name.getText().equals("Ingrese nombre de usuario")) {
//            input_name.setText("");
//        }
//        if (input_password.getText().equals("") || input_name.getText() == null || input_name.getText().equals(" "))
//        input_password.setText("Ingrese contraseña");
    }//GEN-LAST:event_input_nameMousePressed

    private void input_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_nameActionPerformed

    private void input_phoneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_phoneMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_phoneMousePressed

    private void input_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_phoneActionPerformed

    private void input_emailMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_emailMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_emailMousePressed

    private void input_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_emailActionPerformed

    private void input_streetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_streetMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_streetMousePressed

    private void input_streetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_streetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_streetActionPerformed

    private void input_doorNumberMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_doorNumberMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_doorNumberMousePressed

    private void input_doorNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_doorNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_doorNumberActionPerformed

    private void input_street2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_street2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_street2MousePressed

    private void input_street2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_street2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_street2ActionPerformed

    private void input_descriptionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_descriptionMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_descriptionMousePressed

    private void input_descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_descriptionActionPerformed

    private void input_lastNameMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_input_lastNameMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_lastNameMousePressed

    private void input_lastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_lastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_input_lastNameActionPerformed

    private void btn_saveChangesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveChangesMouseEntered
        setColorSaveButton(btn_saveChanges);
    }//GEN-LAST:event_btn_saveChangesMouseEntered

    private void btn_saveChangesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveChangesMouseExited
        resetColorSaveButton(btn_saveChanges);
    }//GEN-LAST:event_btn_saveChangesMouseExited

    private void btn_saveChangesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveChangesMousePressed
        try {
            this.updateUserInfo();
        } catch (SQLException ex) {
            Logger.getLogger(MyInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_saveChangesMousePressed

    public void getUserAddress() throws SQLException {
        String list[][] = new String[1][5];

        Statement statement = reg.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        String sql = "SELECT * FROM \"Direccion\" WHERE \"IdDireccion\" = " + user.getIdAddress() + ";";
        ResultSet re = statement.executeQuery(sql);

        int i = 0;
        while (re.next()) {
            list[i][0] = re.getString("IdDireccion");
            list[i][1] = re.getString("Calle");
            list[i][2] = re.getString("NumeroPuerta");
            list[i][3] = re.getString("Esquina");
            list[i][4] = re.getString("Descripcion");
            i++;
        }

        this.street.setText(list[0][1]);
        this.doorNumber.setText(list[0][2]);
        this.street2.setText(list[0][3]);
        this.description.setText(list[0][4]);
    }

    public void updateUserInfo() throws SQLException {
        String newName = !"".equals(input_name.getText()) ? input_name.getText() : name.getText();
        String newLastName = !"".equals(input_lastName.getText()) ? input_lastName.getText() : lastName.getText();
        String newPhone = !"".equals(input_phone.getText()) ? input_phone.getText() : phone.getText();
        String newEmail = !"".equals(input_email.getText()) ? input_email.getText() : email.getText();

        Statement stmt = reg.createStatement();
        String sqlUsuario = "UPDATE \"Usuario\" SET \"Nombre\" = '" + newName + "', \"Apellido\" = '" + newLastName + "', \"Telefono\" = '" + newPhone + "', \"Mail\" = '" + newEmail + "' WHERE \"IdUsuario\" = " + user.getId() + ";";
        stmt.executeUpdate(sqlUsuario);

        String newStreet = !"".equals(input_street.getText()) ? input_street.getText() : street.getText();
        String newDoorNumber = !"".equals(input_doorNumber.getText()) ? input_doorNumber.getText() : doorNumber.getText();
        String newStreet2 = !"".equals(input_street2.getText()) ? input_street2.getText() : street2.getText();
        String newDescripcion = !"".equals(input_description.getText()) ? input_description.getText() : description.getText();
        String sqlDireccion = "UPDATE \"Direccion\" SET \"Calle\" = '" + newStreet + "', \"NumeroPuerta\" = " + newDoorNumber + ", \"Esquina\" = '" + newStreet2 + "', \"Descripcion\" = '" + newDescripcion + "' WHERE \"IdDireccion\" = " + user.getIdAddress() + ";";
        stmt.executeUpdate(sqlDireccion);
    }
    
    public void disableInputs() {
        input_description.setVisible(false);
        input_doorNumber.setVisible(false);
        input_email.setVisible(false);
        input_lastName.setVisible(false);
        input_name.setVisible(false);
        input_phone.setVisible(false);
        input_street.setVisible(false);
        input_street2.setVisible(false);
    }

    void setColorSaveButton(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColorSaveButton(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JLabel addressTitle;
    private javax.swing.JLabel addressTitle1;
    private javax.swing.JLabel addressTitle2;
    private javax.swing.JLabel addressTitle3;
    private javax.swing.JPanel body;
    private javax.swing.JPanel btn_editDescription;
    private javax.swing.JPanel btn_editDoorNumber;
    private javax.swing.JPanel btn_editEmail;
    private javax.swing.JPanel btn_editLastName;
    private javax.swing.JPanel btn_editName;
    private javax.swing.JPanel btn_editPhone;
    private javax.swing.JPanel btn_editStreet;
    private javax.swing.JPanel btn_editStreet2;
    private javax.swing.JPanel btn_saveChanges;
    private javax.swing.JLabel description;
    private javax.swing.JLabel doorNumber;
    private javax.swing.JLabel email;
    private javax.swing.JLabel emailTitle;
    private javax.swing.JTextField input_description;
    private javax.swing.JTextField input_doorNumber;
    private javax.swing.JTextField input_email;
    private javax.swing.JTextField input_lastName;
    private javax.swing.JTextField input_name;
    private javax.swing.JTextField input_phone;
    private javax.swing.JTextField input_street;
    private javax.swing.JTextField input_street2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lastName;
    private javax.swing.JLabel lastNameTitle;
    private javax.swing.JLabel name;
    private javax.swing.JLabel nameTitle;
    private javax.swing.JLabel phone;
    private javax.swing.JLabel phoneTitle;
    private javax.swing.JLabel street;
    private javax.swing.JLabel street2;
    // End of variables declaration//GEN-END:variables
}
