/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package obligatorio;

import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import static obligatorio.Dashboard.user;

/**
 *
 * @author Antonio
 */
public class MyProducts extends javax.swing.JPanel {

    Connect conn;
    Connection reg;

    private Map<String, String> categoriesMap;
    private DefaultTableModel tableModel;
    private final String[] productFields = {"Nombre", "IdCategoria", "Precio"};

    /**
     * Creates new form Principal
     *
     * @throws java.sql.SQLException
     */
    public MyProducts() throws SQLException {
        initComponents();
        conn = new Connect();
        reg = conn.getConnection();
        this.initTableModel();
        this.fetchCategories();
        this.loadUserProductsTable();
    }

    private void initTableModel() {
        this.tableModel = new DefaultTableModel(productFields, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        this.tbl_products.setModel(this.tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title = new javax.swing.JLabel();
        btn_searchProduct = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_products = new javax.swing.JTable();
        btn_addProduct = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(750, 430));
        setPreferredSize(new java.awt.Dimension(750, 430));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        Title.setText("Mis Productos");
        add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        btn_searchProduct.setBackground(new java.awt.Color(18, 90, 173));
        btn_searchProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_searchProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_searchProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_searchProductMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_searchProductMousePressed(evt);
            }
        });
        btn_searchProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ver Detalles");
        jLabel10.setToolTipText("");
        btn_searchProduct.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 110, -1));

        add(btn_searchProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 150, 50));

        tbl_products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nombre", "Categoría", "Precio"
            }
        ));
        tbl_products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_productsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbl_products);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 700, 190));

        btn_addProduct.setBackground(new java.awt.Color(18, 90, 173));
        btn_addProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_addProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_addProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_addProductMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_addProductMousePressed(evt);
            }
        });
        btn_addProduct.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Agregar producto nuevo");
        jLabel11.setToolTipText("");
        btn_addProduct.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, -1));

        add(btn_addProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 260, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_searchProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchProductMouseEntered
        setColorSaveButton(btn_searchProduct);
    }//GEN-LAST:event_btn_searchProductMouseEntered

    private void btn_searchProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchProductMouseExited
        resetColorSaveButton(btn_searchProduct);
    }//GEN-LAST:event_btn_searchProductMouseExited

    private void btn_searchProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_searchProductMousePressed
        //GOTO EditProduct
    }//GEN-LAST:event_btn_searchProductMousePressed

    private void tbl_productsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_productsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_productsMouseClicked

    private void btn_addProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addProductMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addProductMouseEntered

    private void btn_addProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addProductMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_addProductMouseExited

    private void btn_addProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_addProductMousePressed
        //GOTO Add Product
    }//GEN-LAST:event_btn_addProductMousePressed

    private void fetchCategories() throws SQLException {
        ResultSet resultSet = this.executeFetchCategoriesQuery();
        categoriesMap = new HashMap<>() {
        };

        while (resultSet.next()) {
            categoriesMap.put(resultSet.getString("IdCategoria"), resultSet.getString("NombreCategoria"));
        }
    }

    private ResultSet executeFetchCategoriesQuery() throws SQLException {
        String SQL_QUERY_CATEGORIES = "SELECT * FROM \"Categoria\"";

        Statement statement = reg.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        ResultSet resultSet = statement.executeQuery(SQL_QUERY_CATEGORIES);

        return resultSet;
    }

    public ResultSet executeFetchUserProductsQuery() throws SQLException {
        String SQL_QUERY_PRODUCTS = "SELECT * FROM \"Producto\" WHERE \"IdUsuario\" = " + user.getId() + " AND \"Estado\" = 'false';";

        Statement statement = reg.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
        ResultSet resultSet = statement.executeQuery(SQL_QUERY_PRODUCTS);

        return resultSet;
    }

    public void loadUserProductsTable() throws SQLException {
        ResultSet resultSet = this.executeFetchUserProductsQuery();
        this.tableModel.setRowCount(0);
        while (resultSet.next()) {
            this.tableModel.addRow(this.MapProduct(resultSet));
        }
    }

    private Object[] MapProduct(ResultSet resultSet) throws SQLException {
        ArrayList<Object> productFieldsList = new ArrayList<>();
        for (String field : this.productFields) {
            String fieldToAdd = resultSet.getString(field);
            if (field.equals("IdCategoria")) {
                fieldToAdd = categoriesMap.get(fieldToAdd);
            }
            productFieldsList.add(fieldToAdd);
        }

        return productFieldsList.toArray();
    }

    void setColorSaveButton(JPanel panel) {
        panel.setBackground(new Color(21, 101, 192));
    }

    void resetColorSaveButton(JPanel panel) {
        panel.setBackground(new Color(18, 90, 173));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JPanel btn_addProduct;
    private javax.swing.JPanel btn_searchProduct;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_products;
    // End of variables declaration//GEN-END:variables
}
